# Phase 4: Zero-Focus Native Sync (Holy Grail)

I've discovered the native **`antigravity chat`** CLI! This allows us to push messages directly into your chat session without using flaky UI automation (RPA/SendKeys).

## User Review Required

> [!IMPORTANT]
> This is a **Major Upgrade**. We are ditching the "PowerShell typing" mechanism in favor of the official **`antigravity chat`** IPC. This means the sync will work even if your window is hidden or you are typing in another app!

## Proposed Changes

### [Component] Native CLI Integration

#### [MODIFY] [antigravity.py](file:///d:/Gemini/agent-hand/bridge/scripts/antigravity.py) (The Wrapper)
-   **Method**: `notify_antigravity(message)`
    -   Calls `C:\Users\Administrator\AppData\Local\Programs\Antigravity\bin\antigravity.cmd chat "<message>"`.
    -   This is our "Atomic" delivery channel.

### [Component] Bridge Server (Node.js)

#### [MODIFY] [server.js](file:///d:/Gemini/agent-hand/bridge/src/server.js)
-   **Trigger**: Replace the old PowerShell call with the new native CLI call via the wrapper.

### [Component] Windsurf Knowledge Base

#### [NEW] [sync_architecture.md](file:///d:/Gemini/agent-hand/bridge/.windsurf/memories/sync_architecture.md)
-   **Instructions for Windsurf**:
    -   EXPLICITLY tell Windsurf to use `antigravity chat` via the CLI wrapper.
    -   Declare the architecture: Bridge (3000) -> Connector (8081) -> Native `antigravity chat`.

## Open Questions

-   Should I remove the old `trigger-antigravity.ps1` completely once the native CLI is verified? (Recommendation: Keep as a legacy fallback).

## Verification Plan

### Automated Tests
-   Verify `antigravity.cmd chat "Hello Test"` properly appears in your chat pane.
-   Verify `sync_xxxx.md` is still being generated by the 8081 Connector.

### Manual Verification
-   Trigger a Windsurf sync and see if it "magically" appears in your chat without window jitter.
